storydjango/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('story1/', views.story1, name='story1'),
    path('story3/', views.story3, name='story3'),
    path('story3gallery', views.story3gallery, name='story3gallery')
]

storydjango/rafimorenoppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

storydjango/main/models.py
from django.db import models

# Create your models here.

storydjango/main/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render(request, 'main/home.html')

def about(request):
    return render(request, 'main/about.html')

def story1(request):
    return render(request, 'main/Story1.html')

def story3(request):
    return render(request, 'main/Story3.html')

def story3gallery(request):
    return render(request, 'main/Story3Gallery.html')

storydjango/main/templates/main/Story1.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 1</title>
{% endblock meta %}

{% block content %}
<div class="s1body">
<h1>Selamat Datang di Profile Saya!</h1><div class="profile">
    <div class="s1profile">
        <img src="{% static 'imgstory1/IMG_20190809_1756332.jpg' %}">
        <p>Nama : Ahmadar Rafi Moreno</p>
        <p>NPM : 1906398540</p>
        <p>Angkatan : 2019</p>
        <p>Kuliah : Universitas Indonesia</p>
        <p>Hobi : Nonton Film, Bermain Game</p>
        <p>Deskripsi Saya : Seorang kelahiran 2001 yang sering tidur dan bercita-cita ingin mempunyai perusahaan sendiri</p>
    </div>
    <div class="s1table">
        <h2>Tabel Riwayat Pendidikan</h2>
        <table>
            <tr>
                <th>Jenjang</th>
                <th>Nama Sekolah</th>
              </tr>
              <tr>
                <td>SD</td>
                <td>SD Al-Azhar 17 Bintaro</td>
              </tr>
              <tr>
                <td>SMP</td>
                <td>SMP Al-Azhar 3 Bintaro</td>
              </tr>
              <tr>
                <td>SMA</td>
                <td>SMA Negeri 34 Jakarta</td>
            </tr>
            <tr>
                <td>Perguruan Tinggi</td>
                <td>Universitas Indonesia</td>
            </tr>
        </table>
    </div>
</div>
{% endblock content %}

storydjango/main/templates/main/Story3.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 3</title>
{% endblock meta %}

{% block content %}
{% endblock content %}

storydjango/main/templates/main/Story3Gallery.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 3 Gallery</title>
{% endblock meta %}

{% block content %}
{% endblock content %}

storydjango/main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>about</title>
{% endblock meta %}

{% block content %}
<div class="aboutbox">
    <img src="{% static 'img/CN06.jpg' %}">
    <p>Nama : Ahmadar Rafi Moreno</p>
    <p>TTL : Jakarta, 4 Juni 2001</p>
    <p>Pekerjaan : Mahasiswa</p>
    <p>Kuliah : Universitas Indonesia</p>
    <p>Bidang Studi : Ilmu Komputer</p>
</div>
  
{% endblock content %}

storydjango/main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Homepage</title>
{% endblock meta %}

{% block content %}
<div class="box">
    <h2>WELCOME</h2>
    <h3>This Is Rafi Moreno's PPW Website</h3>
</div>
{% endblock content %}

storydjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
<div id="page-container">
  <div id="content-wrap">
    <nav class="navbar navbar-expand-lg ">
      <a class="navbar-brand" href="{% url 'main:home' %}">RafiMoreno</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:about' %}">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Stories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'main:story1' %}">Story 1</a>
          <a class="dropdown-item" href="{% url 'main:story3' %}">Story 3</a>
          <a class="dropdown-item" href="{% url 'main:story3gallery' %}">Story 3 Gallery</a>
        </div>
      </li>
      </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
</div>
  <footer id="footer"></footer>
</div>
</body>
</html>